### ISSUE TITLE
Cor do mark incorreta quando o horário está no futuro

### ISSUE THREAD

**Issue by marco-jardim** [RioBus/android#10]
Recentemente os servidores da prefeitura passaram antecipadamente para o horário de verão e com isso todos os marks dos ônibus se tornaram vermelhos pois o cálculo do atraso é feito usando módulo. Seria mais adequado mostrar qualquer mark no futuro com a cor verde.

Obs.: ver commit https://github.com/marco-jardim/riobus-web/commit/9ba76403e95971e668a62a1cdd7e3b8d009b4d2c

**Comment by pedrocortez** [comment]
Corrigido no android
