### ISSUE TITLE
Data negativa

### ISSUE THREAD

**Issue by fmsouza** [RioBus/android#19]
Quando o aplicativo de Android acessa a API nova, a data fica negativa devido a problemas na conversão da ISODATE para a data na timezone correta.

**Comment by pedrocortez** [comment]
Como faz com isso? Conserta no android ou no servidor?

**Comment by fmsouza** [comment]
O dado ta chegando certo do servidor, inclusive com a informação da Timezone. Só que o app não ta conseguindo interpretar a informação e pôr o dado na timezone certa antes de operar sobre ele.

**Comment by pedrocortez** [comment]
Vou dar uma olhada essa semana entao.
