### ISSUE TITLE
Implementar suporte a notificações usando Parse

### ISSUE THREAD

**Issue by macecchi** [RioBus/android#26]
Habilitar o app para receber push notifications usando o SDK do Parse. O tutorial de configuração é bem simples:

 https://www.parse.com/apps/quickstart?onboard=#parse_push/android/native/existing

**Comment by macecchi** [comment]
acho que já tá na hora de deletar isto né, plmrdds

**Comment by fmsouza** [comment]
Concordo. Acho até que podíamos ver a possibilidade de iniciar essa parte da cloud direto no Firebase mesmo. Mas isso fica pra depois, quando estivermos prontos pra dar esse passo.
