### ISSUE TITLE
Aumentar traçado do itinerário

### ISSUE THREAD

**Issue by fmsouza** [RioBus/android#27]
O traçado está muito fino, em alguns casos chega a ficar quase que imperceptível. É necessário aumentar a espessura da linha.

**Comment by georgerappel** [comment]
Estou testando agora, aumentando em 50% a largura ela continua um pouco imperceptível em alguns momentos, principalmente porque o mapa mostra trânsito e as vezes tem vias maiores que ficam por cima, como Linha Amarela, Vermelha, etc. Aliás, é uma configuração importante.

**Comment by limazix** [comment]
O importante no momento é ficar visível. Pode não ser muto bonito. Vamos tornar isso configurável pelo usuário, inclusive a cor. Já vou abrir uma issue pra isso.
