### ISSUE TITLE
Corrigir posicionamento do botão flutuante de localização do GPS

### ISSUE THREAD

**Issue by fmsouza** [RioBus/android#34]
O botão se encontrava muito próximo do limite inferior da tela. O commit d0a0b5f950908edb39415b704075a2f1cfa50d83 busca ajustar seu posicionamento com modificação direta no elemento. A configuração deve ser transferida para o lugar correto (dimens.xml ou styles.xml).

**Comment by georgerappel** [comment]
Corrigido pelo commit 0c9f4ac5e6a916ae296f6acb93fea8b4d1d61c80. Acho que já pode fechar.
