### ISSUE TITLE
History view does not shows the "expandable" arrow in some devices

### ISSUE THREAD

**Issue by fmsouza** [RioBus/android#59]
In the "History" view you can see a list of rows indicating the days you have searched for some information in the app. Each line should have the date indication and an arrow indicating that the box is expandable and all the history for the clicked day should show up below the box.

However, the arrow does not shows up, only the day, and it turns out to be difficult to identify that you should click over the box to see the information.

It was tested in two different devices with two different SO versions and did not worked properly:
* Motorola Moto X 2014 (Android 6.0.1)
* Samsung Galaxy Note 10.1 [2014] (Android 5.1.1)

![screenshot_20160322-230135](https://cloud.githubusercontent.com/assets/1396615/13974157/16dc91d4-f088-11e5-832b-1f18fa6c57df.png)

![screenshot_20160322-230138](https://cloud.githubusercontent.com/assets/1396615/13974161/1cbd4e5e-f088-11e5-9bbf-413e30b47a22.png)

**Comment by georgerappel** [comment]
After commit 043976ddaea2fb371bd340ffca12c8c6c0e9ac34 the arrow is the following (tested on Android 5.1.1 and 4.4.4).

![image](https://cloud.githubusercontent.com/assets/7808464/14062717/11250f84-f388-11e5-92d2-6dabfad2d9f1.png)

Should we put it darker or close this issue?

**Comment by fmsouza** [comment]
It's awesome that way.
