### ISSUE TITLE
Showing snackbar with bus sense when searching for multiple lines

### ISSUE THREAD

**Issue by fmsouza** [RioBus/android#90]
When the user searches for a keyword, for example, the result can be buses of lots of lines. This way, the snackbar showing the direction information with the option to change the direction does not make sense.

Suggestion 1: Remove the snackbar for searches with more than one single line as result.

Suggestion 2: Show a snackbar with generic information about the search and the star to favorite the query.

**Comment by limazix** [comment]
The bar only is shown when there is only one result from the search. For example, if you search for 'campo' and there is only one line as result the bar will be showed.

**Comment by fmsouza** [comment]
I should have tested a bad build. Can't reproduce this issue anymore. Closing.
